<div class="image">
	<label><strong>Williams Specialty Company</strong></label>
</div>

<div>
	<nav>
		<ul class="nav">
			<!-- Place links for other pages here	-->
			<i class="fas fa-home"></i>
			<li><a href="index.php">Home</a></li>
			<i class="fas fa-info-circle"></i>
			<li><a href="about.php">About Us</a></li>
			<i class="fas fa-store"></i>
			<li><a href="products.php">Products</a></li>
			<i class="fas fa-phone"></i>
			<li><a href="contact.php">Contact Us</a></li>
			<i class="fas fa-sign-in-alt"></i>
			<li><a href="login.php">Login</a></li>
			<i class="fas fa-sign-in-alt"></i>
			<li><a href="register.php">Sign Up</a></li>
		</ul>
	</nav>
</div>